<?php
/**
 * @file
 * Contains brown_d8react_integration.module.
 * @author James Morton <james_morton@brown.edu>
 */
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Access\AccessResult;

/**
 * App List Function
 * Return list of react apps based on contents of /apps directory
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function brown_d8react_integration_available_react_apps() {
    $current_path =  drupal_get_path('module', 'brown_d8react_integration');
    $apps = array_diff(scandir($current_path.'/apps'), array('..', '.'));
    $options = [];
    foreach ($apps as $app) {
        $appName = pathinfo($current_path.'/apps/'.$app, PATHINFO_FILENAME);
        if ($appName === "sitewide") {
          continue;
        }
        $appNameNice = ucwords(str_replace("-", " ", $appName));
        $options[$appName] = $appNameNice;
    }
    return $options;
}

/**
 * Theme Integration
 * Add paragraph type template to display the chosen react app
 *
 * Implements hook_theme().
 *
 * @return array
 *   Location of template and base hook to see if the template should be used
 */
function brown_d8react_integration_theme() {
    return array(
    'paragraph__react_app' => array(
        'template' => 'paragraph--brown-d8react-integration',
        'base hook' => 'paragraph'
    ),
  );
}

function brown_d8react_integration_page_attachments(array &$page) {
  $canOnlyEditConfig = false;
  $user = \Drupal::currentUser();

  if ($user->hasPermission('edit react app config') && !$user->hasPermission('insert react micro-app')) {
    $canOnlyEditConfig = true;
  }

  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $page['#attached']['library'][] = 'brown_d8react_integration/dreact_permissions';
    $page['#attached']['drupalSettings']['brown_d8react_integration']['dreact_permissions']['canOnlyEditConfig'] = $canOnlyEditConfig;
  }

  $config = \Drupal::config('brown_d8react_integration.adminsettings');
  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    if($config->get('sitewide_app') !== 'none') {
      $page['#attached']['library'][] = 'brown_d8react_integration/'.$config->get('sitewide_app');
    }
  }
}
